version: "3.7"

services:
  weather-app:
    container_name: weather-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8081:8080"
